development:
  adapter: postgresql
  encoding: unicode
  database: portal-2gis_development
  pool: 5
  username: portal2gis
  password: "123qweDSA"
  host: localhost
  port: 5432
test:
  adapter: postgresql
  encoding: unicode
  database: portal-2gis_test
  pool: 5
  username: portal2gis
  password: "123qweDSA"
  host: localhost
  port: 5432
production:
  adapter: postgresql
  host: localhost
  encoding: utf8
  username: portal2gis
  password: 123qweDSA
  port: 5432
  database: portal-2gis_production
  pool: 5
  timeout: 5000
