development:
  adapter: postgresql
  encoding: unicode
  database: portal-2gis_development
  pool: 5
  username: portal2gis
  password: "123qweDSA"
  host: localhost
  port: 5432
test:
  adapter: postgresql
  encoding: unicode
  database: portal-2gis_test
  pool: 5
  username: portal2gis
  password: "123qweDSA"
  host: localhost
  port: 5432
production:
  adapter: postgresql
  host: postgresql5.locum.ru
  encoding: utf8
  username: leondr_portal247
  password: h8NsP7hQ0X
  port: 5432
  database: leondr_portal247
  pool: 5
  timeout: 5000
