development:
  adapter: postgresql
  encoding: unicode
  database: portal-2gis_development
  pool: 5
  username: portal2gis
  password: "123qweDSA"
  host: localhost
  port: 5432
test:
  adapter: postgresql
  encoding: unicode
  database: portal-2gis_test
  pool: 5
  username: portal2gis
  password: "123qweDSA"
  host: localhost
  port: 5432
production:
  adapter: postgresql
  host: ec2-54-217-215-81.eu-west-1.compute.amazonaws.com
  encoding: utf8
  username: pgwobbjwbmpwqs
  password: OWiM7PAYCPFBo0i0M-kizq8M-D
  port: 5432
  database: d16tg1ffjrvabl
  pool: 5
  timeout: 5000
